---
abstract: 'Catalyst plugin to modify C<%ENV> via your application configuration'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Runtime: 5.8
  ExtUtils::MakeMaker: 6.36
  Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Environment
no_index:
  directory:
    - inc
    - t
requires:
  Moose::Role: 0
  namespace::autoclean: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.01
